version: '3'

services:

  postgres_db:
    container_name: postgres_db
    image: postgres
    ports:
      - 6666:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    deploy:
      resources:
        limits:
          cpus: '1'

  neo4j_db:
    container_name: neo4j_db
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: 'neo4j/QWErty123'
    deploy:
      resources:
        limits:
          cpus: '1'

  arango_db:
    container_name: arangodb_db
    image: arangodb
    ports:
      - 8529:8529
    environment:
      ARANGO_NO_AUTH: 1
    deploy:
      resources:
        limits:
          cpus: '1'

  orient_db:
    container_name: orient_db
    image: orientdb
    ports:
      - 2480:2480
      - 2424:2424
    environment:
      ORIENTDB_ROOT_PASSWORD: 'password'
#    deploy:
#      resources:
#       limits:
#          cpus: '0.50'
